---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-github-idp
  namespace: keycloak
spec:
  encryptedData:
    client-id: AgCBQ/6Kj6L+6Xfx8lXVoRdLT94HKoV9g7UrX0JHEwtvmGl/zrhh6ud0yWCV5QPB+1oVpJ5yybpUY3xDxosX/MHrgtWdTXAlYBaBog7dEP8lAhmRBiglXAEXXFSyGMmKMs4u/OGqjYSMC/Dbfd+X6eqcOcgTJj+jbuzqX2yRJNyeYxipYW2GAOrWdX/PRsv/Ze+SSmo/OHV+lyD26hfMFyHUheKBNuA3rnxXgGbQ3vDL53IsG7zIeZHfI8Z206bv9ctk0QGOzATwddDRRoflmXgAFPVeBkLG0Okl4dCvGprieaK+NEryIS9D1cnTUzOf1wRe/DvhAMSjX0TrhX2VOVjLjbNLeQ+8p0RnZS1ItGfwhFSMy9H3aouqOzYYdsPCUCWHZgQ2O55Ek7MIlWIprXLqabu0dsqZdUrKlDFxWYhRTxPXWRLJ1ZYey5tmkbxCJH7/AdJBeTRhipP44OFC6gyYwQ3VvyiRoxXAYelptqoN25FYXM+E9uJBWPbB82CdhmFK85fMl45ANkgJ8Fpw4wH7znPtPIc2/rEVmAMZVmnIPvUykLhZbCl4ChekWNXDmddXxKuyD8jDeeHhIV3ftBs8Dwft+Qlm/B4ToSiPhqsoF7YLpXD1drww2K413+pVtY9+MswzBgWV+Y7ELs3VqbsnQAEltB7VS2jL6eGfuynHn73q9pIxJbnK7u9poAkCyslClNpF6cW5GW6JoOOVEYmbD6dmGg==
    client-secret: AgCMzrxEchscyN2EExv5FQ0zs/+yYVWzNC12u/f+0z+gL/unSSufbGv7130LS8TJ+bJiPcCGTrUD9aLXEzobPdnQUWmoKFRu7/JX/X0hZZFTAhFU3n0t1RpdcBLpNFqJSDE2frR6QnAQm6+WpIEjoBp1F6yC5uJOUzyDRZvwedhYzC7MaSocqKcGlajAIY4yIaS7smpr2oFt2qZ1Aelfb2JO3Gw8rzrHR0J3nl8hjdoas4eHf8pj/HKdFYHsrP2Z8zqSrd1Tyopgt0PlhK05UQ6gAqbuCvlFeuj2qEhsIg3altrrTK6OVKhEZB02r0jqke/QaE7mf1IqDPkhVqI1jlon7aZ8VVs0B/mF46hszA/VyYbpAqe6yNqOsMCjhCm4A7MCamMO5vSSKh9XedgRmWrLL4r4FgOU3H1YHGVo7Wou6/+1x3ukZcNOtayT82vs4owvhtUlZ2qMijM9guZQSHP8S3itmtfyXmM1aCTrmQ7BoYyUK1q/uIoNYlRYbWyW9Bq6oCoCL35RCZ3BywIw7VABT0haiYwBwsoo5p3omuYS4ruknPSzA+hAHef44vZSPPvhTTblZ7fbawr6ZxN92vUj+cQy9k8yc3TQvXtImwRWEk25FV2DshBWbgxM1l1IzYsfrj/hOEdB746QfaoAnyEUEuLtitGF1Q/fe4mxVz/3o7WcR98/odoPn6dbhRpEBzic/nisXJiErjLNBKqH1qLdoJ/oj8QnnJffe/vAAGY0YYmHoie2ofQS
  template:
    metadata:
      name: keycloak-github-idp
      namespace: keycloak
