---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgBgz1RgXBYrP1G+5wz8NpqbKr91w4Ml5SQuhtz4I5++G2TXZSH298c069uUdAasIty1KkBIRRuk9q62AKmvCABUyu/S/67VcBql601mVvIz8RLh/FscPHB5tfVTJzCkbhF4Cw+r+B552i5vBoxwVv2v8CfXPOb1QA+T570syNIJM0zRtHl1sc4oFQwz8VjL5cRjcIU5GCZNDm20SU9WW73OvOfGZwMxMzRn7VrAszNipWjsEVewh8xQC1QT1qUgPnlNMNM6sR5z7UvdTi/f+TfNtRqyfvElbNQlnz87gCt17Lh7/bUNhCvm9YvWwajrEHZl0WixKXwLBnOUJ9A3tiZOLPg/Tu5WBtzIxHrH2vlNiVIyPTyS+2IUTc3pQ+TG7ziTk8kuoCuogHjib/eIYoqBFGJ0rRjjxt4mIfvKLI0nEh+B8xzgZcYu33p8mBaXO8P+iSR4PHk+Nf62I+6/Ls8KEvGFdkOSzv4eJqEUwhNPqNdSlo1ko64yTYIku6F8gCUJA1AZcPUvsJx1kclnBa8/sDQoF1N5z5xhXikMefSByb4jFCLAW3rfgI3vnPGNGXn/O/I7/HGEzefpFbOah4CZs9RB5NXVOoHOIFJ+rj9QWsQxpAsmNItTPVXsaub4vGn7Dq78hOne8jZKR2leA10+M36hIJRkVU1thg1QtHzRT+XYV5KjgSskXn7aMyEB9dJRK/tc6K2LmeIx4vRapajR74FRctIorJw=
    username: AgBxtc+Liy31fc6OrmRHEFPAtC9ibym/deI9qF4b4FrlyYdlDP4ED94VV4wiTOK1QTyiVV2QGyfWINeWmYTcr0A9t5L0PkCeh7IJwpGTwi4r4VTsUuYm8JqhblgeX4djgsnkEFj3srtZMGOMNZW1V8DniVK+4Cow87cuBHNy1Z5WQ4f6iqxD1t4j29njrtWxhRxR8v5ea5UgQ3bPs/5NDcDDqQhAyG8nczwHR4oE4Tlpox/pSL8xkwB9SAPNlJXDefalSU3FrvXpJhUcRHlndQOzvtUjf8RC9oo/UZH1oFaBbmCPgOX8IeoX0cfRqoVQIe80+h9d3/3SG6rYX68PkoikmjSqmAbNZ8mcx9xrA0K7xQxml1RIDXAZKV49Vh5N3G++erRqPputsieeNn8tE5ZDu1nTY0fWuy5QeLxD+TUi2AawH3+nNrMg7CLBOkKMC0VCw34GuCTvKhksrp/1dtT4rCvhinv2riIOV4ooE4nya5qnVJpjbccjIaiHID6Tkw9ffnYKVwECGUEPcyhS00Gm7L+JPnrXdFQtgdpqiE0rjO+XOrrehoIOZ/IdZAgm+qu8b76IUC76IZfqLsQMNsFxNBoU+6sHxUOdomNCQhMD38X3R6HVSy/T/HW+FqHtTQN3VASIR0S1cNmTxYqTwbPlQ1pMwr0SCEK92EEbDkLEay7D+OyzTl4HpSxtBd+Tq6U79pPUtA==
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
