---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    password: AgC+melKH7463kBNEVEn8zLEYuQOoqExQqPdGqoRPnOPZNJ3edYj1Glsdc/6TIymp1OUbeG6zJGxfc3kkGU+UZRXfUT/NocB0oV14Gyg835FQX/r/IMTj8HYSmjAXVzWVj/4aUOM8oWx8m/H58mBI6toeokWGUxrPNxhVBnjXJRoBDZB5o37o72PzAkPgV0fU7Y+Non5PvVvDkssNssxzANgjhzlhRfg5VPDT4hIK7/5E6oFzcBhXA3mxsuaoArvD1+GBr9DielPlMzBjxksQU4Y4JntQTocQDoT1xG+t+bpIP/+pYFXT7AunDUa9JWr3HEJsEUjDKDwU895t3AkEQOEBd75lf+7V3KV7NY4xOMhDJHpCuf7imDGl6y/4WaN5Eq9lP6XlCY5FMFLF4gAhwuXUYCx/P5hYTmFI1h4zc6jjHJNeQ8DhM7y9Ztf6yfa5xnfryN76O/pXiG4F3DKgK8Ipkha/1xrCdqZidfRF8ad19/i+mJAFxZuN8UG7tfS7XWvuvGtydVkjJapKjIqIq4eO1kOwF+nd+VPusXdyLcccpyCA80aGIlX9NtCH5EurTkpHVypxznOONJ+87uyu+lFnszO9qrcO8hi7b1xZF8O7CxoZZviOvmoQ9WY/BNlkspk0XzMOkLGfHDzAGyP2SZbRwbanpGJ+dkcCXC/9IV+g6WPcQmwEedA2aK3876VPCNTleusBZVb41968/GoBp6h/xhVL7LGAa0=
    postgres-password: AgBeRFKQQ0XrR5i8nwUm0+XQM33mmHLsZJgKkhOaPjwB8fmOvV+y0HTZEjFyFHUwWMDR5vPkiHqqNBViF+LWXV87JBqCXMXVyI7gK1iDscOgVO5RtEZwl9GY8HfJj1etD2+A9Gi3TvSXJ96LwXI7uPOPkez1sEYwui24dZzTcbV11aGdDjDXBWni7ibE+AkAiPrf5aLrfqIwXAyutZ546MnqiDsnCquA9FYDPqKRlDBXUVSVnfeTHpeIAc52pTSyUw7+5LeYzyf/NzCVHZyEz61rk9KwljKGc03RjTaGTVIeL1zbQ6M2OaMIbagyyKvD2mENrXvakzCU97I8XlQj48SDT0TMPmv35oJ5BlrXQ50FSqab545Y1UW1DrV6UV6jukUlnI2RiJYGP97HhZ3XrU1kczREZLRvtL5yhzO/CWiPqEHXcEeMGqHlZf7vKUH8XR6WTf12xabNigT91hw/92Rh5myY45T1ZTrwW0Y4LH3JUguxjD4ChokC73NGZYwE+sN17Zgs9WasSR04hu9Cu9k/jMxpy1aQCVfbpGVNxmtfl292z/+7Z4G88Ji09tJVFfxJnwa1ZfrGEj6goCeSywPi1jWvA9uD/YWiZZOEVbEmZkk+vobBOgSjYlW/sKGEJfO4EdC+CTpTwnE7pyncXSRADhDKeX+Ta+jegFtU/3ET+H4wxtMiLyNBw9ogsW8W7vpgxeFEoAIpjJ+Fffl0RxBkEjbrezjge+w=
  template:
    metadata:
      name: keycloak-postgresql
      namespace: keycloak
