apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    # default storage class used for import/clone scratch space when a DataVolume doesn't specify one
    scratchSpaceStorageClass: sata-1tb
