apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld
  namespace: palworld
data:
  TZ: America/Chicago
  PLAYERS: "16"
  PORT: "8211"
  QUERY_PORT: "27015"
  PUID: "1000"
  PGID: "1000"
  ENABLE_PERF_THREADING_ARGS: "true"
  WORKER_THREADS_SERVER: "4"
  COMMUNITY: "true"
  PUBLIC_IP: 172.233.217.64
  PUBLIC_PORT: "8211"
  SERVER_NAME: Noel's Palworld Server
  SERVER_DESCRIPTION: Private Palworld server
  LOG_LEVEL: INFO
  UPDATE_ON_BOOT: "true"
  RCON_ENABLED: "false"
  REST_API_ENABLED: "true"
  REST_API_PORT: "8212"
  BACKUP_ENABLED: "true"
  BACKUP_CRON_EXPRESSION: 0 5 * * *
  DELETE_OLD_BACKUPS: "true"
  OLD_BACKUP_DAYS: "30"
  AUTO_UPDATE_ENABLED: "false"
  AUTO_REBOOT_ENABLED: "false"
  CROSSPLAY_PLATFORMS: (Steam,Xbox,PS5,Mac)
