#!/usr/sbin/nft -f

flush ruleset

table ip game_relay {
  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;

    iifname "eth0" tcp dport 25565 counter dnat to 10.42.0.12:25565
    iifname "eth0" udp dport 19132 counter dnat to 10.42.0.12:19132
    iifname "eth0" tcp dport 25566 counter dnat to 10.42.0.13:25566
    iifname "eth0" udp dport 19133 counter dnat to 10.42.0.13:19133
    iifname "eth0" udp dport 8211 counter dnat to 10.42.0.14:8211
    iifname "eth0" udp dport 27015 counter dnat to 10.42.0.14:27015
  }

  chain forward {
    type filter hook forward priority filter + 10; policy accept;

    iifname "eth0" oifname "tailscale0" ip daddr 10.42.0.12 tcp dport 25565 accept
    iifname "eth0" oifname "tailscale0" ip daddr 10.42.0.12 udp dport 19132 accept
    iifname "eth0" oifname "tailscale0" ip daddr 10.42.0.13 tcp dport 25566 accept
    iifname "eth0" oifname "tailscale0" ip daddr 10.42.0.13 udp dport 19133 accept
    iifname "eth0" oifname "tailscale0" ip daddr 10.42.0.14 udp dport { 8211, 27015 } accept
    iifname "eth0" oifname "tailscale0" drop
    iifname "tailscale0" oifname "eth0" ct state established,related accept
    iifname "tailscale0" oifname "eth0" drop
  }

  chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;

    oifname "tailscale0" ip daddr { 10.42.0.12, 10.42.0.13, 10.42.0.14 } counter masquerade
  }
}
