---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: palworld
  namespace: palworld
spec:
  encryptedData:
    ADMIN_PASSWORD: AgAKpJcK2qD/ySC2nqsa8LEq4CKM+9E3mlvYwAHcLYNvbilHHgByZq6PdPtm2T/RCDzwd5N5g5S81s0La5HxItxM3b1/YM7pA/2eztNVYAdpHwQoO9PAv5Re2tTcMOK1CA4rNJwveAVjevu11PBXir3viKTFcxYSVomciI5UUAC6VVDEexsaqAXkL82BzWauqJRJgYJzR3Ohvhsq9aSp9to5nX5k9kZwNpVLlMYF9zBnMG6lSCPt6TyBxa1VA1mjf3jp8FQIeCB2ffYmhkOzbhOHXcZASi1EghoMfC0V1Co2rb5gEiwglvcGEhfXwDQuq7iiELEfCkUCZYUHzhPLZ1edEZMs0nfoLj9F4McGqARkZiuHfs55Yr1UJAmrMmpwElT26XHyj28ZpjMtOLZ8tCgfIr/6ZKC87UJhFU5gRQC6r98ksOXRTfj4Hg2NGgDGj1eS6RqG/EptXiWO1oRjpqK0vJrhOJVQXexKH0RgsHEQkFOX3VGrPr6qShmIFb+f7LuinKsCyQZIUExvvWPh4NxmW6QQ02/b8QDBpbq6vVX25CJ5/mc03CpUBMVe32jqWo8D/grB6ixvuEiGkYWNrZ+2hop3EWMQ4dwvXE81GB8tHcYE5AkaW+5N5fyIiZ6EqKICUJbbZYL9obtmgz1QYOuF556xj1DzzhA9C77blrqkGdOEUSKPtpCTrsLRCo4AsEnf/WCCwnmGe3VbvtCNVytEMf7yEmH0xgDRe49anRIXvw==
    SERVER_PASSWORD: AgApt1OpLUmi7+68fFj6hYQITnalzpIWOjbJqOwZIRWgeUOX9nr82/ulVpXfM3pav6/ipG7tt8u/hYemsd5t33CBiYYPQcMrxJWwes/6Y4/N2DWHwbt3uSU8uiTvzpGZvl8I7mqLV5aZlSJNYXoLzDnZEhWhZq7OJjt7AkXCWaH7GnAU4MWx84MKFP2DgcRfzUgXWwV/YEkarHEPfJqMLU28N5ZZ6LtNWca7Ohesah++fP2oszhXRZqAKtkdx9EsbId0icF2YtXnK6bQqlZVSZs0EDpNxBtq+M5D3wqQMO8ZQ/1C69CEeRKF9tiaJcdNw/ge0jx8AMbcHaL59FsHUez3WMrncb791YzmcinxHfj6MIbnmg787+6RmtkBSCxOD3K8J9OzLcrlYHazEfh8beq3kqZSdEblmuIeLm2PqLAYwCgNn1CQ+TcZq6v5R2ONG0unO8ZakR9XNaA53rIxL9B9Uz1a0NZgQTT9Y/vZN2OjNBjqeYqTLI/boae85qCPSJSGuHpyZPq0Ru+SodF1CASbZek5IfiNtyHWmfwUpiWM/68OLzhrJ4AJTYRS3lpJ7/MmBFcYuX+kjLEt+oeF8Kv7UFFVOfX9ZoUCc5kF3jGBTa8UlH5Lmz/P5UjV1yDBJfvYP6CnI/txLmtxflCOxTO4cRLOInR/42O7MfwEtcCKDgzo9OVwFuCVP8gCOX+Y/POp9xK4VIAu+vNE41qIxQ9nESvZqQDOti8=
  template:
    metadata:
      name: palworld
      namespace: palworld
