---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgC+IPeHc0r3mgX7Ljk4cO9kv7v5iqXklArqDpFQYOg3YlHmYJH4R6zmUKqFdcRPZ+letV0wIzso4lXx52T/BQj11Zx2NqCjZAC5gMsYlI37+aZOQYZx+4H8FP+JpiT8Nkt0o35X7eC7GQjVO/8DRp+I2lbSMUkURv60w0NeOlMm0szdJzonWTJzDjfM4aDVu9hBcBPOwCLylDLKcjuTOfq1twiSBnXh9wArEb9uLWSHs9J1nxpqopwmBM8ulNf5we61ikL8G2VhRBL162sp6Qjfqsa3fjLEWMsw85olApCjsZMSzRm7gYbKUlS6p7Lho0KLknTLbtBeKJjeOLABCkNe2a/zd/x2ISNJl4bzkMcJ43Uo/SUPqZGNI9uAwh60XWxzHk5vGP6/hnsGBdtv/EVEtg5XkXktaVMa8zKFhT2uZecIrUmArh4iiy5duJvAfjnF2GOVviMFa9DSevaeRLFlKJsZTyWgr8ob1VwdWs5s/L8IPcHs98KvZWzeWjaBe7ZrGhdplsrdJo3BLyQgrtFaSkWCA2ituf7j7XeH5avZGZG95LHCpp8kwustDNm0gZQa6kSH53kLi3O+3ggQN5QGrX7zDXyPZ/St11G47DeZTyncGcoswGskZzRiYKrmkwfveh0wl9+gvbekkc+ACC5wDPRj8ilfTwjoN2CQszXrBktd8U2yIYREFYIzGYpOlp5GvtIsJb8kGrt6C83LQk29
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
