---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-b2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCqHylZ7RJ5Lm27FKaSey/n104h0l+fctD5X1coytsge2RAFiGMTX00fvGSnFH7geZMuzcf3A1o6Df/jnAaLlglG9nAgEmL5I18N4EsOFtFjp+TV5kXZbBYp6yE8vtwORtUk8zlm9u4oD1lKMkz/SATg9nLLceKj5xZsPDTWslPWmIU0NxInnjjMIdUnV5RBlSZdtCN3AylWjiSaBb3VNG1UH54XStvj63BjfuVSfwNOC6dtIa6xxv05TVtS4JUwNeI23VdOtUnhZtGWK1bddPg5PylX/66ty5J/c4lPLnSCDfadxZj3QulWYSWQEzT1NO5Gxu9yJG7mC0XDIJdQFxkiPUxkiMVzY2/AxqTf0NAX55jcjTbgpssMunCrFhn9qs242xYbTcved6Ihi0Iov1vSySZSza1nbEQWu61U1DxFqsj88m+DBCBmbFsd8tnh73xJKBL/aoUOBVO7P7un6T+77zN7zJkfiAcMbRC5FU7xu19q1Uf93rPkbuXGpn4Lby6V7/xF1bjFD5bku7dffn/wNyTBAFjFdYelri2C/Deleocm4rVGIVufuEhZjlIp+RZLgWajF7go6KfcqkDKMsGsU2Z7mejBXl65akl8L7fP0t7bAZvkxcYH3MlJpV5DkwYTuNDAZFuppbqUiFfZ8MHd/YscybjuIIP5TDtN9ENTBGqSCplEdsjxqtSACfO2n0cXFu7qvsbiH2KJkfMvnPD62zRFmGQbchBKQ/MNwrW2edZ/XRLtMI8EyUcwMYFdMBZfzIRdOk9GYl6feJV0P1hxIrHxBRRaVdbvPrhOmaxipBlZelr9PooxkbQYR65s+NjIuGgwpQQfasYSLk=
  template:
    metadata:
      name: velero-b2-credentials
      namespace: velero
