apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtualization
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/noelmiller/talos-homelab.git
    targetRevision: main
    path: 06-virtualization
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: cdis.cdi.kubevirt.io
      jqPathExpressions:
        - .spec.versions[] | select(.name == "v1alpha1")
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
