---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  encryptedData:
    password: AgAoTo16MZUGeayPEAnuzJrCPSjlR+kpvG9dlxrhbCyKrwdGybK02xPLb6IfTIVLiWbgxB9dugMLHUbP06gN20iY/2UNnbjTubWjZzeyou1R4exLyX+cqQnRwb+y5kv7SZtiXsr7w4wD45BVEClKnfaFb2ZrAxdvw+ayv5l3wtjzuOmIjzdr/cIhBiA3IFznDVtfCbYeUD/LHwq39QsKxniGa1OaPCmCFT1MzTMNKVJrL6ZUw4jkV+UzsBAP4YNro1wcNM6NlAJIy97HnRhme6scSU1CDs4abm4BdxH/GRrnzvOYZoEgGyLDkp1m6KMtnqaIpYuMjclCEEP/e8Pn5v577mMpfh7oC4nGEyJa8ZFANH2DJuVh1xzgvJ+j7vqOipGcpxXkJsCsXr9zbY+En965qxIZ+aRHlYwegc3pA1GBiD4dRddymCkwl6CWAFNreU/yoawAMZHEcpCpqR8M3fPT4F0KbHQMCkD37bpmshFYI6zwjkcKbU9Sk0VhcMPEARjo5GKAbwIjARZYoqzJESX6RN9X6F4cvw6aCtHzeJWhTmwwwqudY5v4byq9YaERRjoSugCS9EvoW5LP3FjMcej+Tb8LKLcWmiD0MRyzpT8DpfffkDDJ8tPMdjeoyqFmxO95GSKhMHpLZF+dp568kWVH8FMCrr+qz9M/wHccAZor4W6DSGvO4DmkXGqCoqAmtAMqiwHeMAZQ3/LHCM0wFESXU5FkIzw8Sc4=
    username: AgCLuynVy359kd+VdRTbN+E/0CX6f8qnJ28hDYiUozx7SJDYpPSDxzJpn+AEgt5IDprOKBpSICujRDnyKVbcBcVjSddGqk4B4pMxSUdMh/+7AtHqZBnDv/6aEHAW5XOQvM1nVyku8hs1RvjzHMB4xeohc+vEmNj6fDJW8zQ6tbML9YhC/Wi1kS5y93FpDVr2f5K/PR91PrNqeMRMDfonsI7r3xKlTfpYfuDcPJSNBIGnNcCEMU8l/j1dJx/nz1QWu2FMCoJLbWIO2tnAiEBaQ05yxE8JgDqusIHf6ljqy2eLYMpeIklIs/HWT7e5b3haKQX8rayZU+eOwSXT8DV6BzTMQbcCI4uX2yvmnXMsgdht1lk/bdMXOwu/1TOdF1DIx8WETY4QW0ZDMFJ7mJNrTkw/Fgif/ebjw0ApyMXeObbwsrz5q0m++cOE8S6E4BNe4btJ9UDxBFk8Te+rtssnRV7Olh+z7iMLHFt/Tq1XZ51E5injzLN156avRehOtbwxBPgYN2ZiPKR5xV7HojxNTZxyIHtZqMXHeBjVIJ+spY9D/QJpmIiFYiZg1QV7iZF5ODBFFTD8feZMWWXS/ecJZCrCXOp7OAz4zcZHDVALf/J3CQ0Bnijzuwjqit46AUxwwyjf8Kl7OnV78L1foi2Xklrs/xOOoOO4zLiBsVdwtWwmj/jwh9vVGoxizhCY2pVmDj9oNm/GnW4n+xABjjw6
  template:
    metadata:
      name: forgejo-admin
      namespace: forgejo
