---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-postgresql
  namespace: forgejo
spec:
  encryptedData:
    password: AgBZvQTXDdbWB9uA0g1IyzgBhq3GlCe4/vCSAeNSczQ1qXHkj5EpF5iiTxhDOe3OmEVbUqy8YTqH17klWysEE/cIidWCqwVwH+dz9uA++Q8zcIE5gWFkaUbDbX4U75rMfXfBBCTHfkGi2RoGP+JfU7Df/EgB0sY4z/Nz+Py8ys9kTmDwsQhNmsf223IErAAj/nL8EhQ5rPKz3YBMHfTJB6s1uUVeQfGuM53FfOd/oQ1Rw0I/dZpajTq28T1A1cVwhAS39cKb+1myXLzqMIgNAmrYBSBYcEZH21GVj1G5clFaIAsFbZPuGD1INPWZDRVfU1yr8M6Y/DHHS8e4SKaEwbIuTI/ivtdZddGW+SSJkUsdIzzDlN2wCOjDwfjsiLudOYbvCH1+Nc4XgBMubgW/iC1HKRDHMhwNVgzUTtaiQQFAHANxMKrDyd3Oybjv93Zln3L45nGQ7pIYaHv3xwSFZPZ9U80+sCCkMF6rZ4jbPThTgft8hzBMTdl0dNQB5ZxWIIGh9dzek86KGgS5K7+kLepqryyrAz5KTTloQhvG8fLAH41F6BZR++YeZsn5VQVrJgnhQv+DCh9r44u4jqSTw1LRwwVQsmMhULTIQIy2O0hEDaAhsj+dCvsESMof2YH5dmx6f3+ha3MTlKyn20IxTqXqSHulGLJo/7G40AGipNRmTjVL0e2wG+fF37V7C0Cv2NxupaYtDSuYYzV708QvUrKjJyNGRXsVCp0=
    postgres-password: AgAQ9bFUYHtO/2gVOGLAyMKo+b+9ZYxsKYbBFin6BcOnVKNVDWCdUl86QBdXen/kQK9g6tm7HOlxIkbh2zmrUupfKLhbWUDdT+LjS5A03pX8vZ5To80vBGjeD3LuqqFta1FBqvsb/EWm9JDNHE2IznHQkuyVRcc2GrXebWf8bTpKaWPqS8+NsIkMczBKOG1vMNOICDkB7lMWZMT7AGbNRfcIoYVpQ0BkzZt14hWbQsUNZy8wN5e4fbyM2icMTI2uTQ/OuKmvxVyc97hz8dkonof+JIlePX+C1pET/iSnx1TVWUG8kA5YDANhBgCqXuv3Yp26MqedpnifPRGCFtvXisBuKULvXAT5N2RWH6JHKzyz7H8D+BVdC1mN35M3iQaad1t9pr+lzNmZC8/ygY1uUOPK3Y/r/ByPkMSNpPRLjAcyQy3WFFTKLhOwkC086l/rzSU2yhZuq12M2MPzj8AlJOwRURE+niSVr8HyGjo62soFVXJ0UjqIEJRVFuSqUstv5Sio1WavqbFuHgZxA1Av1uFfMY9iWoHiSpq9zcum5752NmchLWqu3vUkV4lrSXsB2T1BicIPAMNDrDRAXaeTqAkq/htklqU9Hx7osLSBKzgeX1AE3ThNBwvMmpXIUHYlavFdgRbOxtQwEkaKpw7KQM6lqC24fm8k8UC7Bx/skPZUXOQEEYRP6qUSHEK72vi+5hkl491BK+FlLqenTovgIilcGJYbgT2YF8A=
  template:
    metadata:
      name: forgejo-postgresql
      namespace: forgejo
