---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-keycloak-oauth
  namespace: forgejo
spec:
  encryptedData:
    key: AgB3Jzp0UDbWIi3+33KKpfL+HrIIQgE3TZvzPwk8Vl/wumWClcLBlgLKneVJPTpbRnYXKSVJ2DrkjRF4R2mKkkEV/uDZd59ljEz1OzM1qXOzWNNsGMIfZPpQfmW+cVcWUWbu4a3qY9JxDY3eKJqTnx1fU2snaA+IBYvfQmZHnkAKjeQwH3LRv9Yw8NkKuqy/GsUOr5/OyZj/M7uW6f4tB1DOxdP3KM4YFAxaGvnbA4dxy3QsoZHkPOEm4J4tYPWSbW3vLn+AzPW6nirIoVJXGkRkXeKiGSow6i3yODhD4E6440VtsgzXv9jty1ZwIH8QUR0SuhVeK8DTvBV0VAKpWedAoAdyWELvq3cISAsDO4NXvxSjQbCHfFSszsy/QY0vP+TVOROUfmd4aDS5f4Ke81HZM2hJ6c9DTITFa6+hCq5nDxuOTrug5p9kHPR3q23MLPpUPirFoEscEJcBfSbvHVGB1CUXE6ayaxOv4TIsq7PzBxIMUbwmCcRPQvg/MWALqVTYohMGGXr2/qyMx2+bdN8T493tokdlZ6z4mGhDOscrALAgEq7hgypZIxT31rTeaZ7Eqtvb1TSkTYCfclutuAYyUCfVR5pBAtaPPrxMjE33JjhIMVUg/BcI2Ayr3IonxYr5bhW+txdVpAXZnpn0rQLE+kyYsCgns7kV1gkCpsnyIr1F9VtJzFknejFYzl1gjuPVt8orb8ih
    secret: AgAL2q0doXEQ/YIuH8g4s8SFMNVgrg1u3FcfcbLBjXXydRABPkjNMCUYICbt9wRW5QjM05GKwzf/BRFigwrU3l9inyRmvDY07/NANmdj/eoamR1leEG+OuOlmUPXTFRNSPEtjtFXdYds9n8hGJEiKNHv74fwD8uxLHDuTlPccFbaNS9GnoAHY0FjLH5E82wZRCuFfPZeHJELVWMYoNcujoynw1Jb6jU9TzzpvnMeGISYeqAGOC4lAa1BEvWdg+DExlkja1yO0xQEx7eb4FEaqzEU2lGRqEI36B3RproyZK2xctujSkGqbvJqyb5tDZGDiEcg2eDtCogERFTWAmrErFtiCvZMIJAAo/WmXasHqoGqYQWEN7W6y1U54zUcdNZcDdqCMva+KBZlPIXlDeKsV2K/kN/J6jeGrOwqk4ov0rIgF/lSGFGK5vKdm+PPSpLP20lKco5E38OS97hHSp3axV6p1CBXEoIO3s7qpJylUNV3qWmy2r0/IijsT3cZ7HuLZ++ZGLeyuQ+SsqxMC8pg+Ta0FwtPY334XF8g3aVAvKi+izIiqyGtBDxPdslUy2KEolTm5T7SXVyFHMyC4oBfMlkd9rVLhz8wOsy8KdW6qIWQ1MokmFVS3idYw+Jh6Z6lkbETx3ujJtE+S6G2u6sJbNyQrfFH5Gel/nNy4bdVN+qLcbLRhZPoGqwWjjebuu4Qu79jEX9439OnOtJnYMrVwFgBUSIX6EC+8owgM1U/iMqOvPlXcrPwNGzH
  template:
    metadata:
      name: forgejo-keycloak-oauth
      namespace: forgejo
