---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-postgresql
  namespace: outline
spec:
  encryptedData:
    password: AgB24BahQ3j+PKgQ5wKOBrBYI2j4TgAK98ut+ADRRgnNY/tJw3CjefUoBaS7MbW6hELls+WSj5tFcKN/iWp2yo4GwFP6RnqeQQXocrZ00b7D55QipL5AXSXfSfRQWP9CH4UfKeu2OTr3zjpeNYoT5RISSbG/XPzbtDzmVrfAbqc5NZrU6ea4tgk7ckens6kxkBlqVxbgtGWqd0MEcMR3tmbJRqOTfG0l82qfQgNlE7sTWtwS4OIvOtk+B1WzibmJwFN4HSQPya4v5NwTiafSRXyjV2OZSkWdzQSHddaicQ/M0UZnx1kSPBjhl7y9BCjWawz5raZUPTXVvTS0An6SIDz3RFAN+WHKNlECwXgv4ChZXu4/Re2P3FXYW4FIkvCOdClonBB1Pd86JVpzSdoOUn2Bs4vc6lKVYNQ4opsF3Tw7GeNdMGsmFoLheUnzfh4nLYsPxUdvZjoTC5t/0i3oHlaop3C9S+xrWc3iZJRWZX0yWla41aOxhwMCSc2mH+DmexekErtSOwcdmJ3qgwRb1z0svxkDlm71e7n4ibvPTunkg2mOrHcRNsl2w0z6WY+T44ijlgwjn6fI2oW6liDYSSj3VX0udzksLn5Y+qBLzwY3y/6rDjOcg7JklL6Szt8qhwljypB2N2/SZg0R6tUPX9lIQOBe4hwggu+d4CSgeTmSpRBg2PpvvP0ELEPBNnCFJNfVPl5vSChBMSETo5eemCi1r+sufmdEMMoxrtbKOsnx5Q==
    postgres-password: AgAEB7qVB9eLZroHkS134mbL7h9LNEGBoDVEdOsCF0x+O+JB6db6/8aHLf11066dVw6i4mWzA68ou553X2Atih0EP+zczzvSLX6wKyhqsW6RCn0bVr9X26t0BRqflQwuxn6ax4YdcIgm2JfWZABsaNdLQxxlvI+jNiJMvQbxutA5kizWAvtNUILoS2hNem6+t7tXkiIjpjL0kBqMPdq9qcWlr6/YQ/xzN3izWnTtUWugtnMBxxxQwUEo3c/l5Y+7mVNSP3u3HWL3Q60t9dKgSNupN3r77fzU4bYit3fE0ifWlAb1nAV0DNp4tB1O7Z2cvjXv04IjGEe45TCiJ32nWxK3gCj7hy/lvdGHp6XbUvdt/TyaHA9BmHOlng85xPOMFuev1ZXJnqCv7WjgOgMUqfF5gzV/M83W83kZmlPBtzTCAeJVTjd8K50bFyabFfH9j5QqNRbUcd/RJ75Gq9gplPYlCclfW00CqbsvjGXZ7NiJsnQjzlTtZw9Sm+lP32oXMWS+BqKkIctHKi4FOnMmcUlsNnp0XPvvEZSR2LUEvj7jAkmdEihwuqpfmliMssvT9Li2s5l8A6zdhhAdhksMpHv6zs7NICxYKUBCOwLqV/vbNkOmR1mCnSeaDALPXJGOvpY676UoMsJMpGj+WXggBRnF8oJ6NAajqhuFz2/D8mopsXhnlUjkqg2QQRlfpR3sFn43OcbiyYirR0rqgkYa7k5WD7FpHmo9miyac7P+xy4pyw==
  template:
    metadata:
      name: outline-postgresql
      namespace: outline
