apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-creative-rcon
  namespace: minecraft
spec:
  encryptedData:
    password: AgCaw8cSAMnpJWZRyhmf3KDcdYDyLePH31TEYbZJoDPg8m/USnuRZ8wUVI+5a89Xi4bGe/Ob6UDmb6lO1d9fIJkjyqPAh+oBaV2cp863QfWSuuJekOGd1Z1bUmVielL/YeHBp5BUmNBYKRgfrsm5jNQqXP+Fa9y53RqTXYTIyfJg6jmMJbeNZLLz1nhP519p7uDn2nDrFuJlnAoFM1yGaXB3oVG9labqpb0xyJwcEsF5FGX+XR/edQhpHKevmNnmej1+vB69SdZfxcXfEKtU+76PN5WeTFlGzYTqf/g1sba9XcTk7T/hfv5gSoGsvQ32nkcpta0WP1NKuRbmxiR96E+YpZENvkdOLrObP2axB3/ml8c1ddkbksAimF25v59663XnoJEp1OB0LghptrKyozCRxhbHdaZm+b6xV0P0r6vHvn5k7GJwc4lg/dt0sANj+vxmQFoQjd5/Bk5JuR+PB2dZmFnKRLT4YKqKZ9/POdtSyMLO0hwS2AhvYfpYvEBzqRVSmE9lwg1NGnzmB7SNQciFcBjEuBJ13dOkuyD+ls5i3+yXwlU5trjVx1dtLXl8mGJrzRHG6zTv7MnT8LNhlgfF0eYZaxjpeR7L/Z1c5Khd4WN85QxS8xeUVnvZuRTZVsgm7QxfqhLsLAdZOrvyB/ZTtxPPTdmkkLbihksa16/HTl6D0ODjF4WXO8PgA+blFxmli0QDaPqrrMLm7V9T/jwS7biCuHKEEXWGnW0jEeS8S1/rHHJ99wT2S+EgXQ==
  template:
    metadata:
      name: minecraft-creative-rcon
      namespace: minecraft
