apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-rcon
  namespace: minecraft
spec:
  encryptedData:
    password: AgAISYJ4sGKEQFPQccQ8uYS2ieVITKr5KfFMBeoJljLSNT5uqra/z6rURVsqcxIF3j/b5QYOpv0THFSNXXyaBxOoVZTjBrzHGdA95Hkxm5EjJgq0vMl5z1AJ0OtH3x/eJiocdsFe/e1QIYqUro5V2yllUekubunLpEJZul8UuJChccCVWMvigrF/qTz8jEvB8YpTDS16S3eyHssshoG8N8EqoEtid7kBmr84YZNSD1dxJ76/QeKU6Sn1cZkGMxwXFJE06vaWsbtkJLPJrYfBMAY+7tKWc48K0IEE5kKzJ9vEO3sC7hmX4ehD8IChQkXOp+wh3wc1fkA96YL9vAwCXSVLX+W94vBWiY3jFMtBiCwasmZxb9t3P1EZ4cpugdswcSavj9+Is4bWj6J/wIjog1LwGrOVcctfvyJtR+euaTI2obI+o5yFO1IUfURVdyC43z7vCtnyJVuN+8wNAuAyRwpWG86PWpEn6wIhAi8eKyXl5FOel0yAHYhhQnD1c96Jxk6E6NQtBnWrFD4gW0Ncl+tw1H6uCcCm3mpaYNEF/m/3Z0zJqPqLDoehC6534SvhFTvncEess7ZSgbNEmrx7nh02Km59+S+FYaT503PWtq+oY07kZwyLfYomg8THjifkfOfwT3WMap8Om0bCSeVh2oRdBq3uD6gsYNuk4hUFrqS1VilsCz41KchB4dHoS2ZCEdRRTe6gxxp+BVX/jY81jMSuU6NPNWp8auIFbfPjE9YMBmbOdhogpQgf+52qKg==
  template:
    metadata:
      name: minecraft-rcon
      namespace: minecraft
