apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
  annotations:
    metallb.io/loadBalancerIPs: 10.42.0.12
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
    - 10.42.0.0/24
    - 10.99.0.1/32
  selector:
    app: minecraft
  ports:
    - name: java
      port: 25565
      targetPort: java
      protocol: TCP
    - name: bedrock
      port: 19132
      targetPort: bedrock
      protocol: UDP
