apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme-2tb
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-creative-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme-2tb
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-creative-backups
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sata-1tb
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backups
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sata-1tb
  resources:
    requests:
      storage: 50Gi
