apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-namespace.yaml
  - storage-classes.yaml
  - metallb-pool.yaml
  - main-gateway.yaml
  - sealed-cloudflare-secret-cert-manager.yaml
  - cluster-issuer.yaml
  - argocd-route.yaml
  - sealed-argocd-keycloak-oidc.yaml
