---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgA9GIEIu+9qpTRyCqJ6Z4UbMXsF+iPlTv1xXSpR891D0P7DteJbTcF8HtEDJEm6WOe75USfp7YKO5ULfkvjBESkpsXcOenOnj26w/mpXztpZIgYO5Nfxmk+9h7w0GKTHv9fe9LJrniGZdTtQQL7bsNn8GTxb55u1e3XW6Qs2VZkSHMdlRnZTr8AobVRWw2QHDL75S0PVRxT2mmryatApKkGy4CmxJfW5L8WNnL90OfRUlqBFcQA5FZtbW9JtNXYL0mtUzOzsHGrvzVgMnIbqamcwAviwLxh9ez6DMSEXGBtXnAQo6MtdJ0tEHrgN2A+iZ4C3814lXgnVwbjYR2hmj4q3PFbjGz4G/pD5Lo8S9fY2CZdNRK+T/JxHfcY80E5ZE3CfyfN+GgEgcAvL8x9juXJH+K7TpqmfYgiRrUINVgtEgFHqrXpLwv5rYIDfTqJVzcW8dOtOJagpGajWNFh8C4O4UGlYt/civ//zFT0tc8UCC9G63qW2709cAxPyGB4bVtmn3eRfOV1XVGPbtB/umyLvhMoULO8Zg7kpJQr4gHV/Uc6BxL8ysPGA0SxBhCTfsV/EqxwETvrGA8Kqt2nRG+0Kg9W5VvhSPtEQNytlii/e3+/gIy5PHMH1lgkydvt/d+XgCOwkLOuU8uvmDIb+X0SDrICYk9QyLF4HORL8glsibVjT8jQIwASkrSKJmgU1dkBfg4fLKYkwuRCJ6QFgPgn267fnTJs9cIwZeid6xGI/lBe1KU7QeQVYkA4kQPZCI+EagO4kw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
