---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAuuPOKppy4JLcE3Rs5Mm6LgUZSNKS45oTee/nIiTO3ffcmNJYa+brDEVNLj1PmBbbmgFXEXG0vCniL70LxzPZcZ0mru8FC6tbBREq3kmxbCtqi7794wq3PSka0h/hZeyy3mb6CQ3jLHNHSeoC1pJf785tdmv9MJSP3wwvRGdpUiPAeDRokd0BcS3BCGm+tkV9fSJfCXlerMTqXAUUibjSeIizFy4ugKkvwCx4VFzJYv8QYzppo/MQLjywR2fQ1/ftnH7uei2aSr53vsMwHWJmulI2eeDqhixzc0RKv8p207lUJhFxZrfObulgHuGOHeVGDdMpPv3t/0ou9TW6EX+OZzs+L22atBZp3Uu2rb9mI2/YvhyF1yrI9Ti4NSzvakUEOJ94X+gRO1cv/epoRdbbfSyGS/XZrKAqyVHaP7oVXuIMnWZmRQ2lYOWvIkOj9E9/Jo1m+Kq+UmNf2439at7NWkRek/y+udTV4xym7BkzW3K+8JBypZrxGSOHvFUpMgTkqmG6sWknakHar3Hzx8+UMcgcldFES2E+ZBuka96YBFx0M5JmK9VWcpgTQcvDwlaRnIPkPyNK3aSY+RjMVhv0J+SZVTQyNpibF/JWWobdxd9hmARBO55WxghNmNHmp3ECwUyn+aGzITyrypMVBIfTlNuuWt/ek1HmYmVSNdWmnLhiK3pZcNcNO58WkXZimTuNo6ZiYwQI13He3NtsBjGYtUp5RlT9MOKs2wGs6QIysSklZ0dH1jcGpra4eML4PcbeYgRCKKA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: traefik
