---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBh6uHMVzyyV+alnybatC/GpGpUnzIQ+2MPc8U1v45BE0ZXGex6MNQXg0Of8BpCT4GSE0mrHZYFthwRpuPhQIJtbYdK/KXNmpEqhE/2bg737v0WlyeqQbmB7iLRKRwWddvxAl3+JZZ6/nBoymiimWJMHHRGmV50ICQYwvK3JJAGx/l/i82JXXCb7rSG7Vph2T1p9W21LPP4KXCgxLIIG8mexmGgxojdzhfQzuXlxafmNwajAT4d96IFJksSwH4wpo1W1AyVJVrg2xSY0Tsa460EnXL3yQbzw98b6s0EV++fi/0pIKFwg8lIof740JIb6eRHcclFsHkohrkoWXulktgS2Asg6oFJcxSovfnbZQzPpQ7hJu/WvzIEHJgdMLBIsVPi8vXA4vf8x4yqYnkhBApxX80i6j0K6BAPpVB4ENN6PSj9ZHXYfpSoJDmNrYMCgXFAbrGispr93xZ1YZVM4MZacykd9yLzGFSmd1aqb7UfHBba50unf1LdKCF5SzljNUDH854BPYRbt1v8UE61a5MYbMmmef8//U49tIxNG4rIQ9fA5y3cvoR7IGV/dkqyOz6jxrIzA2ZuT5V3IaaRqgMxaI9wVs+K/a9rXsVQv7RlIzWWf83ukW/iCulKpAU5En3hV7zslVWKVs09dEIIcPd1EERJEhWKVSkTAAxG5qugIkEJ+vx3v7beIH7FNf1bdB3JDSumMGYjlXqBj1VxPKOqBljKT41VOi7+qaYOuB8Ztbx+6tBN+o5S72PLKS2o88gRFRi99Q==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: traefik
