---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgDEwxojHncCwXetqRDOMUMrGiVg63U/+NA/SPErmAcIvhvFX+vqC4igzij/ClKIS/eAxwmxcbJnkn2q6hPLjOAj1pOZHzZUs619C7pRpUhltSIEoh4uoVAGRAUEinuJ6VBzhSK4DRHJuVzOxOGw32gCIlW90+WMD40hWHzpnnUUysziV7vVhH/C3l2bNSYf+zzz0f75uD83W610LkRJ8ljddemB9BBVWCU3qWWeAV7vPZ6fmysmcYjeKH/Ogq6O1Ln1s0WXW7xCXvUcdYRLmV8HK4Bm6VLafcZP0qeSmkOQTAL6KFdXLVieMpaqVMhHLuttXYhW1lwy+ieCRe0cijDTE9/IszMeKfs6rWKIN2Ny9zvURYNwCC4zomRY37Xc567Pb38arrrEhF/X5U3XQfbWgmQGp7GgGU9DsRJf3x22RPf03WYRqV8EWVORPZnxm90Ow/eedFzW0VBO0tOEIhyNcEHcRqk+sYl0ew8SWwGD0PqUS7Nz6umNOnNJvwKDuNE7Bj1qVTi/TvpN6y2KvojkbuSzKhvGqDthklEMEdy2I7FDoI2rU27om4IOvHsvANJfG3T05fxzAHLFbUOKv6PDpZ06q/XEKH9i3bfq0BByJrvfZdJ351LE6vZvBwcU+sZJ5/ncRkJ6dyiuJespTkLUaLAzgGkx6u++tCNldkRaDgeFe0sxb7Z+Djbvzs2YQVeo8YOjwKskR1eAFRPxZXexRcFEZsQlV0WDtaWcwvWIG8Cb0DvgoC7bht3M/gs+4yBAF2B/hQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
