---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bookorbit-postgresql
  namespace: bookorbit
spec:
  encryptedData:
    password: AgCSX0hhCnGt4d7tioqO5WAwl+Xy3VdIZi0pgSc/25VKoY3D3U34Yy4GRfxPbAfXSRkxpF6hMYU39R99hOU/Am3KRFUZnbwjh5PaDYp+BbVWB/y9bSdZli5Ez1ZODXbVFW5WkutVyg+sn1RTvrhMWA9CotUPCXiXZWayKwBF1fAQzZLJfdkhSjBqhcjQscH49ngMTwqD9T/g0AZTc36qZ5zIcWjRmXSoRbwz/C0c28rnVPCb8xnlZpqZ7JrF59M+uh45l5glatk6eGyf64ruAJVUn1CkjKS8QTKNf7xTLtmYmCo6rhbKZ5uJ4RqCtJV9yTLtrj5+kCZVKLG0QElLFkJdjB7e2hhpYd4oDMEGpS7T9zgP49CENm0/PYkWtJJ7mJYnEkvLpFfRfDRA5IFegE8zP5fA2IRRh0yslbGwiVq//eoJMzrmooGf36V77H9dyw/TEAralsd9Y7OLMTGgYou6WfdTd9PctYKfis4CCcqj4xYwE9dxtyHETz4M8ARGDxj80ADFReyBGKJrrSOZQ5hrk7eeHDSZH5hzc/8oEaZCwZvnXpYBjqwkbH+ynWH/EJESCInbpjMGiy0SObbhJqt6mf1J/2ISpzi3wqNZX0to1YuaSqS92aj2tqA16jwGFphuwU/EmnAThkz/rYQmnokRVmmDlcbY4y9//SQfQrbUlalryyWcBKblytoGwBxQPGNwdrEG2NfCyuxHiEPe/aIXA5EVQ5O3cVlGuSyPAcqFxw==
    postgres-password: AgCSPemLaz48nITdjdilFFeHP7zKqW8oELG/XbS5f5wLOa2faN8dq7J3DNErhuABXwKlQA0G0TqH4mVAgTyyDjEsWmOXvv0k8VSpmmxxrB1g1pmGlfT2R0xPz6WcdAcO0+XaIkWyIVceg9jixl8x8YXskJc3H7GCV93VpGWTTq061ei9d8fdlfglMEXVY+hRlZcXce8Ien4APg03pfi8lnqHe1no5XDwPi74kRbGcBPGQjZ6WpLQvELV3j2Xr1sDRP2Hi2ruuneiRLd/pkcSCix6WFzBjEJ7iqiqY8SQ/UyDDXGyW7p5ozNgTCqEr5oOzhoKTKBw2vdYCeC0jVBqLS/4jHWmo3vCrVKeZoUuhrdNxuNLgBUr0ptZwtnRrqTwho5MfbjovUztOiGtVOOhDf9lqmCNXMamYOj7yegjxGGB/zN/riEjS0RpI7MOIWHa+FWDkn625lwo+7aqJbJmBVluYDI1OCMqm0ZziUuKf43H5Kg4xyx75RIiQQNOzu8nfA8IAE6+JaJHQHKBmn/IjZFO0RQNWKRBzT83gBKS2T1guVzRxy8dRCzl1TG/uEA4z3JHpMS3NyhM4ob5gNEVeKcgnTzmsuSXcHZ/bA67jbLUOoFyXHL5uN5O8mQBVcDFHQ9/8seuQlCMjvajcZhO9/CDYcNAs/Q7C2Emw6D0z1+MBpU+8F7J31L8K9KGszTGKDHkMqQcwQMGHkojNNtcQaDRZ0J7lw4qjh5PUYzbiVSbQQ==
  template:
    metadata:
      name: bookorbit-postgresql
      namespace: bookorbit
