---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seedbox-ftp
  namespace: bookorbit
spec:
  encryptedData:
    password: AgBGNCf/LJMO+clh7Cefcw983H5mfWNHAgulUXop+ALn7Ib517pDklZv1wKFaOu2XqTxhPvXlUBXPIgTXzkAMAgW4iSCvF6rIVCeP8kYxvevQp3RPKj6u/Azb30M5Ded5Msy5fTYu4Se2Ermcj786AFr1AmuQDFRQxTBRWI4q7nZHyTv0sZGWjjk/MVpT1XxsdMKlh9Dvgs8BkUxras8vDgNi9r+N6Z4Vt7jJPxQHbTZ1I2dH1jSNi73nJUjsSI4Gi98P20C/QiMFjY/agcidqRFUsyN/cbDLIgudynZbYP17h1kILI4LH50w2dOXW2dqMR30gozbKH9FDrygP8nvbpDkI/vUEOm7WW3DQXrnSuyznljM2ZI5n4P9Fh/M7q8gTk8Cd3Ubc2Li4q99g6B5uV8+/ERRTsppbSR9nJKHD9kfLqnT4vhMh7yQuEIg0S9QyqKR0Rr1cfWoB0YqyoZjK5PjzLv5h4BFv/DhnxEwBl5TQpP/Ds5O63lbz1Y/XlUfnP/aWEXzauTnlRw7Kfda7X7mFM4STFDclWtXJmH4DMEgVQIwXQCP/COhG5HBH4RX5VAznCMWkCrMQ+USPwUqSsVAdhAF+X0FVzZ+ZdpXnzyLDlE3oGAUnNytgy6arpEVZz0rGucDKTjuvjiPz65IgGjiExVt9BwYbGCjG6pZM9eENu9drUcaxO/heVPf2ny3RnAwGPN6e+NHribIEY=
    username: AgC2oyzzZh4bh4RxHC4g8sOn4h9BRS3iinAT6FiRDQXVHUTlzieFElqLUhxokptVOy0vJAnQo+2umdsvs1Tzk8pvO6bYJ7LxlgD/9zZY/EZdjMzE7vDdduGjrxLi60DIefhhbrlCIKxu4VMgryNQKJIRLT0kN0OeDqYMAW/Ic6ltTn6Cwa/BtfqVDyXOqnbfxHZjmAzjoyaZPHViQmMYWazlfzUkZFIPKQOUFLWyGrYVvTQIPXkBMtFQCYg0QgqmQvvgm+5FEcO0R88DpM4Phv0y+P/ny+GivXocm1wB85ObvIwaDO/sH+nVwbioAIeGFt80sFQietzqrkMTnKTbu+Cwe/sfu/PaGqHKCF9qFpe6X3E1svBIdjKQMYUKcFNyKvdY64jrreI7cumMlMSoAgry85lHMpc77brq+2YZ9saYQjFVY/C8uSAvPP54jZDPQ9INa2kMI8ShcgqOhjAJ/L4wP1uq621LnjDx6swKl0B6+ECbpdye5FO3UDlkFJkY+NFhtTYDECDqIjVm1DF+sD4/Zfs1RRtFIXOm6JEvO6ePcJTnywZUB2SEgMKYWokn4aP01IzyI5LdRiu2Q70Sqpgmi+jL8cnOTUj97CMu5koEEpW2hQGdz1/UyZWT8NyS7xmhHx1SPAQV3e26/oC+Y0iwWgpKLhnHVtsaDluxxMVR4qKRSMJkJRQA+lBieIgH0xAax+nvpeyBD3cEqz9MW+Z1cA==
  template:
    metadata:
      name: seedbox-ftp
      namespace: bookorbit
