---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-exporter-creds
  namespace: unifi
spec:
  encryptedData:
    password: AgAtwV+XVSOMQ6WHQ/gTtElbf/fFp+arOtQxtZ6cYLXYp74QiLeGLuIxYdt7xQqOpOc/vgbxVZYdl+SprelaObpWfL6HmrqcC2YAOTzDY9OGJfv6CNWT3XoQkqOsxNTUbC+YRgD/0qm46kHy35vgUxX+I9h/BTNpSwjowomnUqcmxjh9ceSHiMq6FiSYxtWCKhb5aIn9OzL+7A9bVd1/QanagCupfGAvth6+lrUimj/YEmnNpxQwIz0yGmBNor2JLjret+06sovfM0sTh+JbJYdSOYfCRn+mwRYThiABjwhtRMGjqdTXR/7x0xE5SDQ4EICf/24aO4ewQ43IcjkyVUgIUUwm8m2CKTy7YxEixKREfRV+7XkpBlDCl2CjStigHD/oTgvoeufE0HhOyznFFl6rOeZOTYHarg2OrCGaTq5f7CRlD7X9LJahvTUGZ7MjhMhq5YINJrsyBj1J8Xvh9kQBHMpIzBCudTn9o6BaWG5frWwVydG5QAoZywm2b4BcQXAj7alZW/QpMEcrKWLI8lcoVUW3nt0EjJwzJ5Wek1J9GPVoGR++xHGj7q1DpUM8UVVC/++tnykHOBuQ3ubLT1lnQrG8paJzqKQOlJbKV4dgBcb/1us35pnNNpnxR3dk9+nBNabWwvQg4CTL2s2AgE5HV/+I2kAvvXVKfEiVSrSvjhDE5HXoBYBPsnimmWbHIWPPltqOFTC4FrmI55hQTQjw5KQE
  template:
    metadata:
      name: unifi-exporter-creds
      namespace: unifi
