apiVersion: v1
kind: Service
metadata:
  name: unifi-web
  namespace: unifi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: unifi
    app.kubernetes.io/name: unifi-os-server
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: unifi-web
  namespace: unifi
spec:
  serverName: unifi.local
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi
  namespace: unifi
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.k8s.noelmiller.dev`)
      kind: Rule
      services:
        - name: unifi-web
          port: 443
          scheme: https
          serversTransport: unifi-web
  tls:
    secretName: unifi-k8s-noelmiller-dev-tls
