---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-discord-project-webhooks
  namespace: n8n
spec:
  encryptedData:
    project-webhooks: AgBO55mTzekmW3mkTLyBMnytoKHPIpSrnPPlAWbJFA1EUNP72yLv3jNhTj+NDZj6B0h1aYSfDsns3k53paWZoJur7OdrBE1LiG8I9uJqEcgmYR30TDrP1EgS9OdSzPJyP5bOEBqD4ZU5mERt2q6Z5syZ73yFM1NMYFPYJSytHw2Smtqct5WGB1VPCLMC0Q9RD4rE0eXbSpuHs8x4qsvUSlV8CDCJ2g9Eb/4SPmpI+Ubzp80jARPi7WdJWMJClmHcePMc9g2PXmTRzjV3vVgUV34SrfbGWjVOM2o8wLUetlGkKJ5i5SrlaTF7J3N35C3pTfPZYILg26Sk8GMvDDta7EasTr/01F2maIXk1YlK9xQvJa9pYi/4dk7LPfDLFMd9m2ybOvZQdStn4cCy6Wh9l9PbeMVjWEPd92h9dnYrp87WGW0qvuE+a/ovV8hSeeQV0ot3mmy3WPDgdfuaE7u1DsH9d2PEols4BsjwXFl8gPFeMu2f1aJT8Fasf0XcmROpVXF+QTQMPmb2DGcSycktr0XLwBOdNE+me1EC5MWtW22vLsiUqpV8HLiq60XWcGdbRtH/+EphDTp59h17+3mRwmftFf6Z9z9wjDWMjOHCv/FZZSXQFEK26TTx8rBFBElrzrLel1GggHlfxVp9bQpjuhz/euqJugDAhlfZUQS4HVcTJ4dFvi6jWRmF7xibCA8QP3fsODTU/KZBTOwUuIsqagb/hl6mv/1Fr5MOPW9Ww76ORkT8FQpty4QeKmz4xpIoAZk68wuo6By991qIj9GEvs3A1+VUjHtNFuR62R5Yw7zyAIQzppC6FO18yz2owaKlepNDK1k00g/fj4EtiayorCGgvK7F93WYrLaVT6vqGGBB2Lf8rA0l4puOB3Uw2EsBTkRlsoPxuNLXYv1YMoYCosAMl2oFF5RKQeqpuMZPfQ8ZSqvpXG4JHrOzmwbE/Mrns/0K2iD61GTnpEvmkHXK6NsSxf9XlB8D1ZIwByUwPUbDlqAqOnap0TgPEAyqHTZ8nPgLdpQUKm/jPDshoYfgGrDCgqpZDlkbkh/bA0cd7lpZOCEYevSWDDQzmvMXnXO02fucY0tNnQYNLvHxFvrE8cNVTW/lPIUaf3PGHGDjGCBQ/JP0nUJ9hNO19Msii852zpVSZ5MQietWEutxCAwADx7jFtckiiIyN/eE1Bc227olYTt6ikd2stxAVO8So3Y12eOYW4zWySJHRL/fqWFXByd3k8SsGj8=
  template:
    metadata:
      name: n8n-discord-project-webhooks
      namespace: n8n
