---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-discord-interactions
  namespace: n8n
spec:
  encryptedData:
    guild-id: AgA6UAHjFt/mrlfeP59E22Mi04tyEGWuBnN4ZUrAbhm08thCmMUMNuWiKd/5xh6qWmn6gNYwWKJvJxbJsfvM8H9+5uluYUav4fOMOSw/n9w1ELziYzWRhJRmDA08PL8Bh9uVLJ1FohZCeuTlBU6kjcnBcO57HMK/1XqFGL/Cf/+3pDU9AXy3xVKcHwTZ9HW8BhgmZv7nn0Z+2AG0luZCdEHr8slCj4DdyXnAw1SWKD58q6i14hPrNOH4I2pBELyuzMpR3JYFI0WytBe0E8yB2SVbGRHfObHW231bUU8mQw8xw48dHO2RG1+RldcB9C3fuxsL1idWqHlH3ZT1mhMLBkkS6hlFKNIWkCprDD7Ib/o4sdrx6aJmbTVy0scrtytzOl9CjA1ynydeBWwx3bVimhQrAF3TGfe10HeevS0O79hLY4EaH/v5tolSzAz/FPurPA0pU2mJJaCfHoxVwq1pdjglRN8i8KthpG1hLSbFGeHEjTBlBSewAGR92qxehrLULJkiDoDkYm0zvUcS8hXJ5UPKr0wzPOB9hxK1yKoqE/+p757Znp8JoWqfVVF5plkGuvywLCwd+o80SdsvKquX0WVT12XyNnKbfAtxHPWAtGT30RD9NK6klpEAGYUPaA39qy87rvNv97LCOzH7vmWbbxvxxSNTi3Zb2nqlUbEXVEVPgEfwilN9c/HBdjhQfi5vI0bweayZndTHHdqRn7cOL4bVVUM=
    public-key: AgA2DLQjTelAATC96dJX3CZbePnm0hnz7gRzu7q+v96LqDarfqQqb+QFOt+CqQeAZcI5ULq2e+fooDRSH/bT7kP/LuG5KL3iAnI4j7W60dN02EhSmBV0Gb0mAtKYcTUdcVbvir+z/wlZ0rlUn/0NTov8EJFWgHli7F4hMIfu/9sTTZiqZwvZ8r+TOyPHuizA+8WuO9Q6QCc25e6apni45C5OPh1p0CMZzOX9QidDorLC0MiKGhbNnhsDj8SbjhNrqXrSGSlRtG8qqbqD9wljRw00r0HIVHOJJm0GVRKPQmjma2gifR2hgRXxmXLd+H2IcLyM+bMQSYYcnj9BMZLuRNxts9krgE9LE9AlsOPVHq4ScmF304QS3lc0RTZXI97du2OGrWfqIjLEF8GMKETmDQ9m0lIyKzxov+Mevf47xn+wDyhVaU+gdUsLBzFh+5EThfpUshMVhIjk3IRY1L60MmXAvorYp5B+O7/qlJUsVVNm0kd+pt2NI3FgDrW6SFn6Kgpu+CYOd+41TKCXL7v1SIqeV0NYlEPItaMhBlqjfxIm17X/SIq9z6umFrOoXLbNKr35zksgA4f3XKxgsFvp2cmqOawYQLrfGluq5EITBUGhhCRxzsqROIdKY/lfCYrML0PbjpI5YeXYWy+UtsQVXuRv2+SBKLAUPRhmg+GC9A/HJsDprQjFCuDb9CegJK665621ReuyMiJ5r6kfL4kafO1wawgXFYXIWpFIZwTeDN08G6rVRPntzLgpv+lUQZKdGvp7fci9hw15ZI5+O89UbRJW
  template:
    metadata:
      name: n8n-discord-interactions
      namespace: n8n
