---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgresql
  namespace: n8n
spec:
  encryptedData:
    password: AgA1d6S56oqWHmZ54QjLf6IVyK1XjZtgKJ6rExa2u15Be99OmN4hyJ0UxZ4kZHJnA+yj89opgBkMXlyDuaJ42XrjtTADABEkOPhbG8I5Inxn0U151feyHo8qtKvgeTC2j+jglvrsBadVFLYsIM7w2/M++KbY4geQjf7Axtnx5FRQzzc8F714znuLAZV1J92xo4/QON6fsqa158227xbdVZMa9kZ25DxKY7dnQTqfzuwLhJYJwD5bkIRsown/vOlcjzcwzoj+CEiYFBmLyvyUtst+FFqsY8F7GDyFg4bVXPxG+0ChZtiMfZje1rcEn/emg0Yt0r02gRzxHkAvuKYwQsymsC1JiVxBsJtZFr6Z5kxmVcNPAjgiDxJi3POErGdOsQ04M+1YWQ9AGtEMJQYQvTa3Enin8a7P4Q3/qNWpQgbvCnq+VwPXJ+VmHTiM5zjdy55Pu+kdEdrNYdL9hTSRYIT0hOkzY2kloMCYKF/ycUixGqZ/E3onCTESvzV8J4Lf3sY5IVq/xjjmnX4aG/fTlTqHOcMOW10wwBRc7A2z9I8+ClWySBqWcWp4lvElcLbnFtdH82eT81doxTvstFzawO031OGqVf3iZBrBJGPdGYmqIqks+0AJYvqN50SWCZP61sL5lnNnPcKaxPLtbC5ZNF+ZYlGKu1u6sCIlB/jOSzJcvVpFRHpe8282sdEqvlCKekXNY/nL75A+0Ywwl5aPsSf6C+iKi9Myp9g=
    postgres-password: AgBasCzNiaX9eq3c73Lxes3/GUUvQlfvQSYQskM5OGiYn9qGB9Vs1Vmk21iTBCdgt4CrfXR2B0c67bKdX0bEyERfiKb5iXfcygbbFi53osJppr8hIXcgcl0qkwTcOdL8OwrPXhjYvIJebtUNlVQpQnu9IIsWHIMhAiVfmzZVr6NgjUBesVPQKkcnz9PVyKC+ZShYersLPY2vVdKDdl34ySnvMYgUMC8Yvv+T+N7UKAPXyL/7vucK6AGO1C3g9+/IWx929aTAsnZREFMZYZ0TGO+UqQUQat1L2HYnhmIrjFuUIFdYLlOdb6Ywlj747TlU60gzBirP4nIrV2U9v1T6UCEeJOiZzlre57NwN+HUmPlEEMn/msNvQIOFpO0Jc7ArAj4SMV0VYlHJPURFL9RPVOs+c7LtG5LskEDFxeIumUJ89D0gCpBwp28r2pd81IB7zHAMMS6nChZ+Q2D34dJ9cbpWmIRkH3+w103cY1vnNlAPPZ5/oYTJPABs/Hoaivz2qFztvkJh1PyfZ6vypSXceHYgjGY36riitmVIPY8jNGQGmOfU7u/7YhG6oBUr2voszU0oz1yUh4kdO2F5Y286DG/FS98L6VnGZc049ZJCXlwg1+16E7+3MKVEBDhdYAQlBvBSvviUwjylDda1owcIeOSDX3yKxoh/xr4DzLEIa3OBel75vbyN9XhZTXI5Znz8XXON/90znczPp6humGv272dX4Zy3svIAhIw=
  template:
    metadata:
      name: n8n-postgresql
      namespace: n8n
