apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - jellyfin.yaml
  - sabnzbd.yaml
  - sonarr.yaml
  - radarr.yaml
  - prowlarr.yaml
  - bootstrap-job.yaml

configMapGenerator:
  - name: media-bootstrap-script
    namespace: media
    files:
      - bootstrap-script.sh
