apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    # linuxserver.io images run as root during init to chown volumes to PUID/PGID
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
