---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ombi-mysql
  namespace: media
spec:
  encryptedData:
    mysql-password: AgAra8r/k2BX6eiK7RaO7J5ol3u3CYzYTQ8yUtRkrOOW/Qicild85OhJ32KAaDh1S3HH+6gHXPGN0axsaGkWgLR4zswZUOdm4XZhIjAiMbmZRnc3Ga2it9iuziMv99JMOm1zD6xo96oRESj/95rAWKs0HwZoeCbYb+KyU2BhCGwgtSr2KjiipHJ7kb9lx0SPZvqPlMQPFcfABCJAgDAf8X7m7LR61Y2UEmOiHTOLdmn29VYXebRAYvGHruZjtjg3l0O4bIihbhZhceLhICDjIJXf/BZhLe13ppby6YWjsd8xYGAjSS/Eoyc0I2MVUvmPll72nFQ9GZe1jJL2WHMY32gKeQdtcIqH3jfJ4oCPiMvq9jdCUirYeJS0oLUh7s/Ij11HB2DQIbhSfUnravaOh6REEf9MjFKlRDKeN3AxwdcShJBYZ/d2K1xWOOdcUbZbBc8X8fKHxfQvS3OMQWYkcXtyhM6zr5E0krTr6DEXY1ropXZpLhY51SXsQFxkkJsfc4YZbPjzgiODJKEjuxZwHpzaAa8FVZrV9DhcIzTkq5oYaq5aR6Jn7wR1TONs9Jtg23W1wVtbrLwz1szbm2ouLsjpFZsXB2FA5TobMrJ0h0+WQpeyKsbt0sWCKFTnCNwPz1cTuzY47xCcUh53upKc6DZ5vueivCnGUWBxR6lxJWPhHxDYDB/hZ/RDiucFDwJJX/lFVhCh1LR68txrMMwZ2H6W6/vFv5iWAhsfUu/5zwHmYDKfqXHUfLOXZ9LrZWmUEupysv3xBfIzmeCA6kcYywav
    mysql-root-password: AgB01PUIrTu7SHSHIQNmyMX7r0ghcbpoHT06dbPS8G5D+wValcnvwke0K+3eDvb5+9nYbFWJkhkrSBi7zTbweyp6SgBsVZtwS03OH1t/kAjpLcJ33vEuZPtUUSMGPWKmUMSVck1h1yai8tv+55v2n4vuo9U1r4eI8FnuG896vjowytjfjLKMvqct5a5mmNAbD59HYm7GhNrKxezr1bQnsOsU+A6oFAG45wevnCtS/fUmwSu65Vm9joF0MAqFMokxO3Qy5uXEHFePLVNhKUWjKyDkWvjabsXhQPR+f4gpjqloL/j3Za0Hfkc2mQWR4aB2IWPlbwMPKRX7kujuqDafHTxgdompAFR1iNM8+aEZ1IdN4ee6kyVW+cv3KRTmpx7AArTART9G3LbRXZeYZJzr1dmSV7dgnL9zkC7PmZWjHQfyN/2+ZQmbAdK4B/4AUbw241oQj+wyUpYG8zvf/N+nuhGnLW7tu0UhuxFMR14kgkCeLcIlp20VqQBY+suu8B7/rlB1+5JOWRorw6MuFVseiQ5GnJrrGt8002NbJlUIqMdysi3kkXZVq00UZMRZ2SPuVJgJvXsUQ27QdMoQGghBiO5UhIUg4MC3tytvoeALwjjjEzNQDNtMP/9Wm8HLrJmwyXBcy6YDsJUWVKK8Toaq7ww9N3YRcysVoWZZ9V9+RVk3oOglSFiQNhKdQmE+EP7nQsGn7n4HWpqqEAskgZSS3ygHloYYBY9WnIiXpOdwziaw2q8lU9zSq6/sgd8xHqdUSHhb1bBDqrXhJKmJwkRbV/sh
  template:
    metadata:
      name: ombi-mysql
      namespace: media
    type: Opaque
